export const wallets=[
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fatomic.svg`,
        name:"Atomic"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbinance.svg`,
        name:"binance"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbitcoin-beach.svg`,
        name:"bitcoin-beach"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbitcoin-core.svg`,
        name:"bitcoin-core"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbitcoin-com.svg`,
        name:"bitcoin-com"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbitfinex-icon.svg`,
        name:"bitfinex-icon"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbitpay.svg`,
        name:"bitpay"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbitstamp.svg`,
        name:"bitstamp"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbittrex.svg`,
        name:"bittrex"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbitzlato.svg`,
        name:"Fbitzlato"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fblixt-wallet.svg`,
        name:"blixt-wallet"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fblockchain-wallet.svg`,
        name:"blockchain-wallet"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fblockstream-aqua.svg`,
        name:"blockstream-aqua"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fblockstream-green.svg`,
        name:"blockstream-green"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbluewallet.svg`,
        name:"bluewallet"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fblw.svg`,
        name:"BLW"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbrd-wallet.svg`,
        name:"brd-wallet"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fbreez.svg`,
        name:"breez"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fcashapp.svg`,
        name:"cashapp"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fchivo.svg`,
        name:"chivo"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fcoinbase.svg`,
        name:"coinbase"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fcoinbase-wallet.svg`,
        name:"coinbase-wallet"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fcoincorner.svg`,
        name:"coincorner"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fcoinomi.svg`,
        name:"coinomi"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fedge-wallet.svg`,
        name:"edge-wallet"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Felectrum-wallet.svg`,
        name:"electrum-wallet"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fenjin.svg`,
        name:"enjin"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fexodus.svg`,
        name:"exodus"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fguarda.svg`,
        name:"guarda"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fklever.svg`,
        name:"klever"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fkraken.svg`,
        name:"kraken"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fkucoin.svg`,
        name:"kucoin"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fkucoin.svg`,
        name:"Fkucoin"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fledger.svg`,
        name:"ledger"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Flocalbitcoins.svg`,
        name:"localbitcoins"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fluno.svg`,
        name:"luno"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fmuun.svg`,
        name:"muun"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fmycelium.svg`,
        name:"mycelium"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fnicehash.svg`,
        name:"nicehash"
    },
    {
        item:`https://www.bitrefill.com/content/cn/v23/wallets%2Fpaxful.svg`,
        name:"paxful"
    },

]